name: Docker Multi-Architecture Build

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://codeberg.org/teddit/teddit.git ${{ github.workspace }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: cache docker cache
        uses: actions/cache@v2.1.3
        with:
          path: /tmp/cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}-
            ${{ runner.os }}-docker-
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 1337kavin/teddit:latest
          cache-from: type=local,src=/tmp/cache
          cache-to: type=local,dest=/tmp/cache
