name: Empty Commit Pusher

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git config --global user.email "20838718+FireMasterK@users.noreply.github.com"
      - run: git config --global user.name "FireMasterK"
      - run: git commit --amend --allow-empty --no-edit
      - run: git push --force
